# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a792d25a37a5c9b85bcf1673fc6353b23fc5ae8f02d4801c649e46f99bc13b9b18dfbe96c2dbaa379dff7c579fabbb9214708143c90d694acb211cf42b5c5bb7

test:
  secret_key_base: eade54d1ae49fe801f656127305b55dfa93b75a1eed4bca6114f83dce9ee538f3f3d579fdd32d27d810891fc7281ab8575905e0e80051c8e8bf4998ec3d2ddea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
